apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterControllerIdentity
metadata:
  creationTimestamp: null
  name: default
  namespace: openshift-cluster-api-guests
spec:
  allowedNamespaces:
    list: null
    selector: {}
