apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: okd-cs4l2
  namespace: openshift-cluster-api-guests
spec:
  clusterNetwork:
    apiServerPort: 6443
  controlPlaneEndpoint:
    host: ""
    port: 0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: okd-cs4l2
    namespace: openshift-cluster-api-guests
status:
  controlPlaneReady: false
  infrastructureReady: false
